import { InvalidStateTransitionError } from './errors.js';

export const dentalCaseStatuses = [
  'DRAFT',
  'RECORDS_PENDING',
  'INTAKE_REVIEW',
  'ADDITIONAL_INFORMATION_REQUESTED',
  'MATCHING_IN_PROGRESS',
  'CLINICS_SHORTLISTED',
  'TREATMENT_PLANS_PENDING',
  'TREATMENT_PLANS_READY',
  'CONSULTATION_SCHEDULED',
  'CONSULTATION_COMPLETED',
  'PATIENT_DECISION_PENDING',
  'BOOKING_PENDING',
  'BOOKED',
  'IN_TREATMENT',
  'TREATMENT_COMPLETED',
  'AFTERCARE_ACTIVE',
  'WARRANTY_CASE_ACTIVE',
  'CLOSED',
  'CANCELLED',
] as const;

export type DentalCaseStatus = (typeof dentalCaseStatuses)[number];

const transitions: Readonly<Record<DentalCaseStatus, readonly DentalCaseStatus[]>> = {
  DRAFT: ['RECORDS_PENDING', 'INTAKE_REVIEW', 'CANCELLED'],
  RECORDS_PENDING: ['INTAKE_REVIEW', 'ADDITIONAL_INFORMATION_REQUESTED', 'CANCELLED'],
  INTAKE_REVIEW: ['ADDITIONAL_INFORMATION_REQUESTED', 'MATCHING_IN_PROGRESS', 'CANCELLED'],
  ADDITIONAL_INFORMATION_REQUESTED: ['RECORDS_PENDING', 'INTAKE_REVIEW', 'CANCELLED'],
  MATCHING_IN_PROGRESS: ['CLINICS_SHORTLISTED', 'CANCELLED'],
  CLINICS_SHORTLISTED: ['TREATMENT_PLANS_PENDING', 'MATCHING_IN_PROGRESS', 'CANCELLED'],
  TREATMENT_PLANS_PENDING: ['TREATMENT_PLANS_READY', 'CLINICS_SHORTLISTED', 'CANCELLED'],
  TREATMENT_PLANS_READY: ['CONSULTATION_SCHEDULED', 'PATIENT_DECISION_PENDING', 'CANCELLED'],
  CONSULTATION_SCHEDULED: ['CONSULTATION_COMPLETED', 'TREATMENT_PLANS_READY', 'CANCELLED'],
  CONSULTATION_COMPLETED: ['PATIENT_DECISION_PENDING', 'TREATMENT_PLANS_READY', 'CANCELLED'],
  PATIENT_DECISION_PENDING: ['BOOKING_PENDING', 'TREATMENT_PLANS_READY', 'CANCELLED'],
  BOOKING_PENDING: ['BOOKED', 'PATIENT_DECISION_PENDING', 'CANCELLED'],
  BOOKED: ['IN_TREATMENT', 'CANCELLED'],
  IN_TREATMENT: ['TREATMENT_COMPLETED', 'WARRANTY_CASE_ACTIVE'],
  TREATMENT_COMPLETED: ['AFTERCARE_ACTIVE', 'WARRANTY_CASE_ACTIVE', 'CLOSED'],
  AFTERCARE_ACTIVE: ['WARRANTY_CASE_ACTIVE', 'CLOSED'],
  WARRANTY_CASE_ACTIVE: ['AFTERCARE_ACTIVE', 'CLOSED'],
  CLOSED: ['WARRANTY_CASE_ACTIVE'],
  CANCELLED: [],
};

export function allowedCaseTransitions(status: DentalCaseStatus): readonly DentalCaseStatus[] {
  return transitions[status];
}

export function canTransitionCase(from: DentalCaseStatus, to: DentalCaseStatus): boolean {
  return transitions[from].includes(to);
}

export function assertCaseTransition(from: DentalCaseStatus, to: DentalCaseStatus): void {
  if (!canTransitionCase(from, to)) {
    throw new InvalidStateTransitionError('dental-case', from, to);
  }
}
