export const systemRoles = [
  'PATIENT',
  'CAREGIVER',
  'DENTIST',
  'CLINIC_STAFF',
  'CLINIC_ADMIN',
  'CONCIERGE_AGENT',
  'VERIFICATION_OFFICER',
  'SUPPORT_AGENT',
  'FINANCE_ADMIN',
  'CONTENT_ADMIN',
  'PLATFORM_ADMIN',
  'SUPER_ADMIN',
] as const;

export type SystemRole = (typeof systemRoles)[number];

export const permissions = [
  'profile:read:own',
  'profile:write:own',
  'case:create',
  'case:read:own',
  'case:read:shared',
  'case:read:assigned',
  'case:read:any',
  'case:transition:own',
  'case:transition:assigned',
  'case:assign',
  'case:share',
  'matching:read:own',
  'matching:manage:own',
  'concierge:queue:read',
  'concierge:case:manage',
  'concierge:supervise',
  'clinic:read',
  'clinic:manage:onboarding',
  'clinic:manage:team',
  'clinic:manage:cases',
  'clinic:manage:availability',
  'clinic:manage:services',
  'clinic:read:analytics',
  'clinic:read:billing',
  'document:read:own',
  'document:read:shared',
  'document:read:assigned',
  'document:upload:own',
  'document:upload:assigned',
  'treatment-plan:author',
  'treatment-plan:accept',
  'booking:create:own',
  'booking:read:own',
  'booking:read:clinic',
  'booking:manage:clinic',
  'verification:read:own',
  'verification:read:any',
  'verification:submit',
  'verification:review',
  'verification:approve',
  'verification:audit',
  'verification:suspend',
  'payment:read:own',
  'payment:manage',
  'incident:create:own',
  'incident:read:own',
  'incident:read:assigned',
  'incident:manage',
  'review:create:own',
  'review:respond',
  'review:moderate',
  'privacy:request:own',
  'content:manage',
  'audit:read',
  'privacy:manage',
  'admin:impersonate',
  'system:manage',
] as const;

export type Permission = (typeof permissions)[number];

const patientPermissions = [
  'profile:read:own',
  'profile:write:own',
  'case:create',
  'case:read:own',
  'case:transition:own',
  'case:share',
  'matching:read:own',
  'matching:manage:own',
  'document:read:own',
  'document:upload:own',
  'treatment-plan:accept',
  'booking:create:own',
  'booking:read:own',
  'payment:read:own',
  'incident:create:own',
  'incident:read:own',
  'review:create:own',
  'privacy:request:own',
] as const satisfies readonly Permission[];

export const rolePermissions: Readonly<Record<SystemRole, readonly Permission[]>> = {
  PATIENT: patientPermissions,
  CAREGIVER: ['case:read:shared', 'document:read:shared'],
  DENTIST: [
    'clinic:read',
    'clinic:manage:cases',
    'clinic:manage:availability',
    'case:read:assigned',
    'case:transition:assigned',
    'document:read:assigned',
    'document:upload:assigned',
    'treatment-plan:author',
    'booking:read:clinic',
    'incident:read:assigned',
    'verification:read:own',
    'verification:submit',
  ],
  CLINIC_STAFF: [
    'clinic:read',
    'clinic:manage:cases',
    'clinic:manage:availability',
    'case:read:assigned',
    'case:transition:assigned',
    'document:read:assigned',
    'document:upload:assigned',
    'booking:read:clinic',
    'incident:read:assigned',
  ],
  CLINIC_ADMIN: [
    'clinic:read',
    'clinic:manage:onboarding',
    'clinic:manage:team',
    'clinic:manage:cases',
    'clinic:manage:availability',
    'clinic:manage:services',
    'clinic:read:analytics',
    'clinic:read:billing',
    'case:read:assigned',
    'case:transition:assigned',
    'case:assign',
    'document:read:assigned',
    'document:upload:assigned',
    'treatment-plan:author',
    'booking:read:clinic',
    'booking:manage:clinic',
    'incident:read:assigned',
    'incident:manage',
    'review:respond',
    'verification:read:own',
    'verification:submit',
  ],
  CONCIERGE_AGENT: [
    'concierge:queue:read',
    'concierge:case:manage',
    'case:read:assigned',
    'case:transition:assigned',
    'case:assign',
    'document:read:assigned',
    'document:upload:assigned',
    'incident:read:assigned',
    'incident:manage',
  ],
  VERIFICATION_OFFICER: [
    'verification:read:any',
    'verification:review',
    'verification:approve',
    'verification:audit',
    'verification:suspend',
  ],
  SUPPORT_AGENT: ['case:read:assigned', 'incident:read:assigned'],
  FINANCE_ADMIN: ['payment:manage', 'audit:read'],
  CONTENT_ADMIN: ['content:manage', 'review:moderate'],
  PLATFORM_ADMIN: [
    'concierge:queue:read',
    'concierge:case:manage',
    'concierge:supervise',
    'case:read:any',
    'case:assign',
    'verification:read:any',
    'verification:review',
    'verification:approve',
    'verification:audit',
    'verification:suspend',
    'payment:manage',
    'incident:read:assigned',
    'incident:manage',
    'review:moderate',
    'audit:read',
    'privacy:manage',
    'admin:impersonate',
  ],
  SUPER_ADMIN: permissions,
};

export const privilegedRoles = [
  'DENTIST',
  'CLINIC_STAFF',
  'CLINIC_ADMIN',
  'CONCIERGE_AGENT',
  'VERIFICATION_OFFICER',
  'SUPPORT_AGENT',
  'FINANCE_ADMIN',
  'CONTENT_ADMIN',
  'PLATFORM_ADMIN',
  'SUPER_ADMIN',
] as const satisfies readonly SystemRole[];

export function permissionsForRoles(roles: readonly SystemRole[]): ReadonlySet<Permission> {
  return new Set(roles.flatMap((role) => rolePermissions[role]));
}
